server:
  port: 8085

spring:
  datasource:
    username: user
    password: user
    url: jdbc:postgresql://localhost:5470/user-post
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  mvc:
    throw-exception-if-no-handler-found: true
    static-path-pattern: /resources/**
    resources:
      add-mappings: false

jwt:
  secret: my-secret-key
  expiration: 360000

