server:
  port: 8085

spring:
  datasource:
    username: user
    password: user
    url: jdbc:postgresql://localhost:5470/user-post
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
jwt:
  secret: my-secret-key
  expiration: 360000
